# Generated by Django 4.2.10 on 2025-12-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='WOMA Sportswear', max_length=100)),
                ('site_tagline', models.CharField(default='Engineered for Performance', max_length=200)),
                ('logo_url', models.URLField(blank=True, max_length=500)),
                ('favicon_url', models.URLField(blank=True, max_length=500)),
                ('hero_title', models.CharField(default='ELEVATE YOUR GAME', max_length=200)),
                ('hero_subtitle', models.CharField(default='Premium sportswear designed for champions', max_length=300)),
                ('hero_cta_text', models.CharField(default='Shop Now', max_length=50)),
                ('hero_cta_link', models.CharField(default='/shop', max_length=200)),
                ('hero_background_image', models.URLField(blank=True, max_length=500)),
                ('primary_color', models.CharField(default='#9333ea', max_length=7)),
                ('secondary_color', models.CharField(default='#db2777', max_length=7)),
                ('accent_color', models.CharField(default='#f472b6', max_length=7)),
                ('background_color', models.CharField(default='#000000', max_length=7)),
                ('text_color', models.CharField(default='#ffffff', max_length=7)),
                ('about_title', models.CharField(default='About WOMA Sportswear', max_length=200)),
                ('about_description', models.TextField(default='Reimagining sportswear through a lens of modern utility and uncompromising performance.')),
                ('about_image', models.URLField(blank=True, max_length=500)),
                ('instagram_url', models.URLField(blank=True, max_length=500)),
                ('tiktok_url', models.URLField(blank=True, max_length=500)),
                ('twitter_url', models.URLField(blank=True, max_length=500)),
                ('youtube_url', models.URLField(blank=True, max_length=500)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_address', models.TextField(blank=True)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('show_newsletter', models.BooleanField(default=True)),
                ('show_chat', models.BooleanField(default=False)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Website Settings',
                'verbose_name_plural': 'Website Settings',
            },
        ),
    ]
