# Generated by Django 4.2.17 on 2025-11-28 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productvariation_variationimage_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variation',
            field=models.ForeignKey(blank=True, help_text='Specific product variation ordered (e.g., Red-Large)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.productvariation'),
        ),
    ]
