# Generated by Django 4.2.17 on 2025-11-30 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_convert_to_dynamic_attributes'),
        ('orders', '0002_alter_orderitem_unique_together_orderitem_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variation',
            field=models.ForeignKey(help_text='Specific product variation ordered (e.g., Red-Large)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.productvariation'),
        ),
    ]
