# Generated by Django 4.2.17 on 2025-11-28 17:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('material', models.CharField(blank=True, max_length=50, null=True)),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, help_text='Additional price for this variation (can be negative)', max_digits=10)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='products.product')),
            ],
            options={
                'db_table': 'product_variations',
                'ordering': ['color', 'size'],
            },
        ),
        migrations.CreateModel(
            name='VariationImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField()),
                ('is_primary', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productvariation')),
            ],
            options={
                'db_table': 'variation_images',
                'ordering': ['display_order', 'created_at'],
                'indexes': [models.Index(fields=['variation', 'is_primary'], name='variation_i_variati_8dabc2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='productvariation',
            index=models.Index(fields=['product', 'is_active'], name='product_var_product_87b3ae_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariation',
            index=models.Index(fields=['sku'], name='product_var_sku_0936bf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariation',
            unique_together={('product', 'color', 'size', 'material')},
        ),
    ]
