# Generated by Django 4.2.17 on 2025-11-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productvariation_variationimage_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_categor_9e60b3_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_slug_5e91f2_idx',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='name',
            field=models.CharField(blank=True, help_text="Custom variation name (e.g., 'Premium Edition'). Leave empty to auto-generate.", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0, help_text='Base stock (used only if no variations)'),
        ),
    ]
