# Generated by Django 4.2.17

from django.db import migrations, models


def migrate_to_attributes(apps, schema_editor):
    """Migrate color/size/material to attributes JSON."""
    ProductVariation = apps.get_model('products', 'ProductVariation')
    
    for variation in ProductVariation.objects.all():
        attributes = {}
        
        # Build attributes from existing fields
        if variation.color:
            attributes['Color'] = variation.color
        if variation.size:
            attributes['Size'] = variation.size
        if variation.material:
            attributes['Material'] = variation.material
        
        # Generate name from attributes or use "Standard"
        if attributes:
            variation.name = ' '.join(attributes.values())
        else:
            variation.name = 'Standard'
        
        variation.attributes = attributes
        variation.save(update_fields=['name', 'attributes'])


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_variation_name'),
    ]

    operations = [
        # Remove unique_together constraint first
        migrations.AlterUniqueTogether(
            name='productvariation',
            unique_together=set(),
        ),
        # Add attributes JSON field
        migrations.AddField(
            model_name='productvariation',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Custom variation attributes as key-value pairs'),
        ),
        # Make name required with default
        migrations.AlterField(
            model_name='productvariation',
            name='name',
            field=models.CharField(default='Standard', help_text="Variation name (e.g., 'Red Large Premium')", max_length=200),
            preserve_default=False,
        ),
        # Migrate data
        migrations.RunPython(migrate_to_attributes, migrations.RunPython.noop),
        # Remove old fields
        migrations.RemoveField(
            model_name='productvariation',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='size',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='material',
        ),
        # Update Meta
        migrations.AlterModelOptions(
            name='productvariation',
            options={'ordering': ['name']},
        ),
    ]
